ci: Release builds for Haiku and Linux

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -279,3 +279,67 @@ jobs:
         with:
           name: stage3.haiku
           path: ${{ github.workspace }}/stage3.haiku.tar.xz
+
+  release:
+    needs: [stage3, stage3-haiku]
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
+      - uses: actions/checkout@v6
+
+        # TODO: There may be a race condition here if multiple builds complete at the same time.
+      - name: Determine Build ID
+        id: buildid
+        run: |
+          latestRev=""
+          today=$(date --utc +%Y%m%d)
+          releaseUrl="${{ github.server_url }}/${{ github.repository }}/releases/tag/llvm-gcc2-$today."
+          pageNum=1
+          while [ -z "$latestRev" ];
+          do
+              json=$(curl -fsSL                                   \
+                  -H "Authorization: Bearer ${{ github.token }}"  \
+                  -H "Accept: application/vnd.github+json"        \
+                  "${{ github.api_url }}/repos/${{ github.repository }}/releases?page=$pageNum")
+              pageNum=$((pageNum + 1))
+              if [ $(echo $json | jq length) -eq 0 ]; then
+                  # This means that we've passed the end and reached an empty array
+                  break
+              fi
+              if [ $(echo $json | jq 'objects // {} | has("message")') == "true" ]; then
+                  # API has return an error object
+                  echo "Unable to fetch releases from GitHub API"
+                  exit 2
+              fi
+              # Store array of revisions
+              revisions=($(echo $json | jq -e -r ".[] | .html_url | select(contains(\"$today\"))[${#releaseUrl}:]")) \
+                  || continue
+              latestRev=${revisions[0]}
+              latestRev=${latestRev%-*}
+          done
+          if [ -z "$latestRev" ]; then
+              latestRev=0
+          fi
+          latestRev=$((latestRev + 1))
+          echo "buildid=$today.$latestRev" >> "$GITHUB_OUTPUT"
+
+      - name: Download Stage 3 Artifacts
+        uses: actions/download-artifact@v8
+        with:
+          pattern: stage3*
+          merge-multiple: true
+
+      - name: Rename Artifacts for Release
+        run: |
+          mv stage3.tar.xz llvm-gcc2-${{ steps.buildid.outputs.buildid }}-linux.tar.xz
+          mv stage3.haiku.tar.xz llvm-gcc2-${{ steps.buildid.outputs.buildid }}-haiku.tar.xz
+
+      - name: Create Release
+        if: ${{ github.ref == 'refs/heads/master' }}
+        uses: softprops/action-gh-release@v3
+        with:
+          tag_name: llvm-gcc2-${{ steps.buildid.outputs.buildid }}
+          name: LLVM for GCC2 Binaries Build ${{ steps.buildid.outputs.buildid }}
+          make_latest: true
+          files: llvm-gcc2-*.tar.xz
